apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-spring-boot-app
  labels:
    app: dish-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dish-spring-boot-app
  template:
    metadata:
      labels:
        app: dish-spring-boot-app
    spec:
      containers:
        - name: dish-spring-boot-app
          image: swapnilsalvi/dish-spring-boot-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/dishapp"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: dish-spring-boot-app-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # You can choose any available port in your cluster
  selector:
    app: demo-spring-boot-app