version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-dishapp-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dishapp
    ports:
      - "5433:5432"
    volumes:
      - /Users/swapnilsalvi/Desktop/finaldbdata:/var/lib/postgresql/data
  app:
    build: .
    image: dish-web-app
    container_name: dish-web-app-container
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dishapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db